Repository CLUSTER-DS-Club/cluster, pull requests merged in 2025-06, with the labels that each got.

#32 Fix #13 , Adjust padding and positioning in HeroSection for improved Responsive…
  src/components/home/HeroSection.jsx
Labels: SSOC S4, BEGINNER, Contributor, Approved

#46 Created the Contact us page and the Backend api for that and also created the email templates for User Confirmation and Team Alert about New Query Received
  backend/package-lock.json
  backend/package.json
  backend/server.js
  index.html
  public/404.html
  src/App.jsx
  src/components/common/Header.jsx
  src/components/contact/ContactPage.jsx
  src/main.jsx
  src/pages/Home.jsx
Labels: SSOC S4, INTERMEDIATE, Contributor, Ready for merge, Approved

#38 Add FAQ page with accordion, categories, search and routing
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Footer.jsx
  src/components/faq/CategoryFilter.jsx
  src/components/faq/ContactPrompt.jsx
  src/components/faq/FAQAccordion.jsx
  src/components/faq/FAQPage.jsx
  src/components/faq/QuestionItem.jsx
  src/components/faq/SearchBar.jsx
  src/components/faq/data/faq.js
  src/components/faq/hooks/useDebounce.js
  src/components/faq/hooks/useLocalStorage.js
  src/components/home/HomePage.jsx
Labels: SSOC S4, INTERMEDIATE, Contributor, Ready for merge, Approved

#82 Bug in Contact Us
  src/components/contact/ContactPage.jsx
Labels: SSOC S4, BEGINNER, Contributor, Approved

#108 solved bug #102 issue
  src/components/contact/ContactPage.jsx
Labels: bug, SSOC S4, BEGINNER, Contributor

#120 🌐 [Page]: Documentation #45
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/documentation/CodeBlock.jsx
  src/components/documentation/DocSection.jsx
  src/components/documentation/SideNav.jsx
  src/components/documentation/TableOfContents.jsx
  src/pages/Documentation/CLICommands.jsx
  src/pages/Documentation/Contribute.jsx
  src/pages/Documentation/Documentation.jsx
  src/pages/Documentation/DocumentationLayout.jsx
  src/pages/Documentation/SetUpSteps.jsx
  src/pages/Documentation/TechOverview.jsx
  tailwind.config.js
Labels: SSOC S4, INTERMEDIATE, Contributor, Approved
